### PR TITLE
Readiness

### PR DESCRIPTION
**Pull request by kalantar**
Initial implementation of readiness task.  See https://github.com/iter8-tools/iter8/issues/1190.

### CODE REVIEW

**Comment by sriumcp** [comment]
The earlier `kubectl` based implementation of the readiness task had multiple issues... among other issues, we couldn't really unit test it (the previous attempt didn't actually have a unit test which tested the readiness logic; instead only peripheral stuff like name-length was unit tested).
***
Perhaps we can use the dynamic go client to `get` the resource in question...  like in these examples... 
***
Dynamic client example (List): https://itnext.io/generically-working-with-kubernetes-resources-in-go-53bce678f887
Another (Get): https://caiorcferreira.github.io/post/the-kubernetes-dynamic-client/
***
For checking conditions, perhaps we can marshal the unstructured object into [JSON ](https://pkg.go.dev/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured#Unstructured.MarshalJSON), and unmarshal back to 
something like 

```go
type Resource struct {
  Status: Status
}
```

```go
type Status struct {
  Conditions: []Condition
}
```

where Condition is [here](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties)
```go
type Condition struct {
  Type               FooConditionType   `json:"type" description:"type of Foo condition"`
  Status             ConditionStatus    `json:"status" description:"status of the condition, one of True, False, Unknown"`

  // +optional
  Reason             *string            `json:"reason,omitempty" description:"one-word CamelCase reason for the condition's last transition"`
  // +optional
  Message            *string            `json:"message,omitempty" description:"human-readable message indicating details about last transition"`

  // +optional
  LastHeartbeatTime  *unversioned.Time  `json:"lastHeartbeatTime,omitempty" description:"last time we got an update on a given condition"`
  // +optional
  LastTransitionTime *unversioned.Time  `json:"lastTransitionTime,omitempty" description:"last time the condition transit from one status to another"`
}
```

This should basically let us filter the "True" conditions, and check if the given condition type has status set to true.

```yaml
- task: k8s-object-ready # note: singular object as opposed to plural
  with:
    delay: 3 # delay in seconds before first check; optional; default 5s # optional with default
    retries: 10 # number of attempts to check conditions; optional; default is 12 # optional with default
    retryInterval: 3 # time between attempts in seconds; optional; default is 5s # optional with default
    kind: deployment # required
    apiVersion: v1 # required
    name: hello-there # required
    namespace: default # required
    conditionType: Ready # optional
```

**Comment by kalantar** [comment]
Rewriting using unstructured APIs is doable. I've marked as draft while this is done. In the meantime this implementation allows us to play with the API and begin to think about what changes to the charts look like.

**Comment by sriumcp** [comment]
Makes sense...

This PR is relevant to the chart design -- https://github.com/iter8-tools/hub/pull/10

Relevant part of the PR is here: https://github.com/sriumcp/hub/tree/k8s/testlibchart/load-test-http/templates

In particular, the `testlibcharts` folder shows how the experiment charts themselves can be drastically simplified (literally containing only 10 or 20 lines of helm template code or less), through the use of a library chart which provides commonly used templates.

**Comment by kalantar** [comment]
closing; will reopen with version using k8s dynamic client

**Pull request closed without merging**
