### PR TITLE
V0.2 merge

### PR DESCRIPTION
**Pull request by kimikowang**
1. Support service type of baseline/candidates
2. Use unique id for versions identified by analytics
3. Enable integration tests on travis
4. Remove unused test files
5. Reconstruct experiment router code base
6. Rename cache to adapter

### CODE REVIEW

**Comment by kalantar** [comment]
I observe that we've renamed the candidates as `candidate-n`. See value of `CURRENT BEST`. Why did we make this change? I find it harder to understand. Can we go back to using the deployment/service name?

```bash
$ k -n bookinfo get experiment
NAME                 TYPE     HOSTS       PHASE         WINNER FOUND   CURRENT BEST   STATUS
reviews-v3-rollout   Canary   [reviews]   Progressing   false          candidate-0    IterationUpdate: Iteration 2/8 completed
```

**Comment by kimikowang** [comment]
> I observe that we've renamed the candidates as `candidate-n`. See value of `CURRENT BEST`. Why did we make this change? I find it harder to understand. Can we go back to using the deployment/service name?
> 
> ```shell
> $ k -n bookinfo get experiment
> NAME                 TYPE     HOSTS       PHASE         WINNER FOUND   CURRENT BEST   STATUS
> reviews-v3-rollout   Canary   [reviews]   Progressing   false          candidate-0    IterationUpdate: Iteration 2/8 completed
> ```

Candidate might have duplicates. While traffic split returned from analytics is in a form a map, where keys must be unique.
Assessment for each version in status have both name and id. Name is the the name of deployment/service. The printer can redirect that from id to name.

**Comment by kalantar** [comment]
> Candidate might have duplicates. While traffic split returned from analytics is in a form a map, where keys must be unique.
> Assessment for each version in status have both name and id. Name is the the name of deployment/service. The printer can redirect that from id to name.

Could the change to the printer be included in the PR then?

**Comment by kimikowang** [comment]
> > Candidate might have duplicates. While traffic split returned from analytics is in a form a map, where keys must be unique.
> > Assessment for each version in status have both name and id. Name is the the name of deployment/service. The printer can redirect that from id to name.
> 
> Could the change to the printer be included in the PR then?

I forgot that we have changed the printer. No, this can not be done directly.

**Comment by kalantar** [comment]
> I forgot that we have changed the printer. No, this can not be done directly.

Why can't it be done directly?

**Comment by kimikowang** [comment]
> > I forgot that we have changed the printer. No, this can not be done directly.
> 
> Why can't it be done directly?

This is the value returned from analytics. If we want to show the actual name, then the code needs to go over the candidate lists and find the match.
The more important thing is, the purpose of id is to give unique names to the versions. If duplicates exist, showing the name of the version may not be accurate.

**Comment by kalantar** [comment]
The id has no meaning to the user so isn't helpful. We should not be showing it to the user as part of a print. We will need a different approach or solution. If it is an index to the list the user provided as input (`service`) then I think it is sufficient.

**Comment by kimikowang** [comment]
> The id has no meaning to the user so isn't helpful. We should not be showing it to the user as part of a print. We will need a different approach or solution. If it is an index to the list the user provided as input (`service`) then I think it is sufficient.

It's an index, just with `candidate-` added as prefix. For example, `candidate-0` means the candidate at index 0. But I agree that showing this might not be helpful, we can remove it.

**Comment by kalantar** [comment]
> It's an index, just with candidate- added as prefix. For example, candidate-0 means the candidate at index 0. But I agree that showing this might not be helpful, we can remove it.

We made the decision to include the `CURRENT BEST`. Even it is just and index, we should be able to translate this to something the user understands. If we feel we cannot, we need to have a wider discussion about what appears in print.

**Comment by kimikowang** [comment]
> > It's an index, just with candidate- added as prefix. For example, candidate-0 means the candidate at index 0. But I agree that showing this might not be helpful, we can remove it.
> 
> We made the decision to include the `CURRENT BEST`. Even it is just and index, we should be able to translate this to something the user understands. If we feel we cannot, we need to have a wider discussion about what appears in print.

Why do think that user can not understand `candidate-0`?

**Comment by kalantar** [comment]
If a user can understand what it refers why can't we tell them explicitly?

**Comment by kimikowang** [comment]
> If a user can understand what it refers why can't we tell them explicitly?

I answered it in a previous thread. If duplicate exists(e.g. both candidate 0 and candidate 1 refer to `reviews-v2`), showing `reviews-2` can not tell it's candidate 0 or candidate 1.

**Comment by kimikowang** [comment]
For the printer issue, we can have a discussion later. But I do not think this affects this PR. If you think it is not a good way to show the candidate, I can remove it from the printer column right now and let's focus on other parts of the code. @kalantar @fabolive

**Comment by kalantar** [comment]
It affects the PR because this PR breaks the video that we plan to show for kubecon. It breaks the tutorials we have written as part of our slack campaign. We have to decide that this is acceptable before agreeing to merge the PR.

**Pull request merged**
