### PR TITLE
Linkerd Helm tutorial

### PR DESCRIPTION
**Pull request by Alan-Cha**

### CODE REVIEW

**Comment by huang195** [comment]
@Alan-Cha I'm trying out the tutorial, and ran into this issue

```
$ helm install my-app iter8/linkerd \
  --set baseline.dynamic.tag=1.0 \
  --set candidate=null  
Error: failed to download "iter8/linkerd" (hint: running `helm repo update` may help)
```

I'm guessing the iter8/linkerd chart hasn't been added to our helm repo yet? What's the workaround here?

**Comment by huang195** [comment]
On the plus side, linkerd installed flawlessly this time. I looked at the rest of the tutorial, and it looks pretty clean.

**Comment by Alan-Cha** [comment]
@huang195 You can reference your local files.

```
cd iter8/
helm install my-app ./helm/linkerd \
  --set baseline.dynamic.tag=1.0 \
  --set candidate=null  
```

> On the plus side, linkerd installed flawlessly this time.

The irony is that nothing changed 😆

**Comment by huang195** [comment]
@Alan-Cha oh the charts are in the repo itself. Good to know!

**Review by huang195 — APPROVED** [review]
@Alan-Cha /lgtm. The only nit I have is the experiment being 10 iterations of 10 seconds each is a bit of an overkill. Maybe reduce it to 2-3 iterations. Feel free to merge without the change.

**Review by sriumcp — APPROVED** [review]
lgtm

**Pull request merged**
