### PR TITLE
update workflow action versions

### PR DESCRIPTION
**Pull request by kalantar**
Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

### CODE REVIEW

**Comment by kalantar** [comment]
We continue to have a problem with the staticcheck job. The action dominikh/staticcheck-action](https://github.com/dominikh/staticcheck-action)@v1.2.0 uses the deprecated `actions/cache@v2` internally. While the source for the action has been updated, there has been no new release.

We can either continue to use for now or comment out the check (we are using the staticcheck plugin in our lint checking as well).

**Review by sriumcp — DISMISSED** [review]
LGTM

**Comment by sriumcp** [comment]
> We continue to have a problem with the staticcheck job. The action dominikh/staticcheck-action](https://github.com/dominikh/staticcheck-action)@v1.2.0 uses the deprecated `actions/cache@v2` internally. While the source for the action has been updated, there has been no new release.
> 
> We can either continue to use for now or comment out the check (we are using the staticcheck plugin in our lint checking as well).

Great catch. Lets get rid of it since `golanglint-ci` covers static check also.

**Review by sriumcp — APPROVED** [review]
LGTM

**Review by Alan-Cha — APPROVED** [review]

**Pull request merged**
