### PR TITLE
remove need to clone

### PR DESCRIPTION
**Pull request by kalantar**
I've updated the documentation to remove the need to clone the repositories. However, it relies on the addition of a yaml file for install of iter8-analytics for knative since this is different from the install for istio.

### CODE REVIEW

**Comment by kalantar** [comment]
Addresses https://github.com/iter8-tools/docs/issues/11

**Comment by kalantar** [comment]
prereq for this is https://github.com/iter8-tools/iter8-analytics/pull/23

**Comment by fabolive** [comment]
@kalantar: I pushed a few enhancements to your branch here. Please, take a look.
Also, I have a comment. Right now, we ask the users to import the Grafana dashboard, which can only be done if one clones the repo(s). Could you, please, modify the installation instructions to tell the users to run your script https://github.com/iter8-tools/iter8-controller/blob/master/hack/grafana_install_dashboard.sh to import the dashboard? We can tell the users to manually import if they cannot run the script properly.

**Comment by kalantar** [comment]
Good idea. Currently it assumes the config file is local. I think we will need to modify the script to get it from the repository instead.

**Comment by kalantar** [comment]
Updated `grafana_install_dashboard.sh` (to allow use of URL when specifying the config file) is defined by PR https://github.com/iter8-tools/iter8-controller/pull/49. It should be mreged before this one.

**Comment by kalantar** [comment]
@fabolive Please take another look

**Pull request merged**
