### PR TITLE
Gitops

### LINKED ISSUE #943: Drop `Helmex-update` in favor of `run` and make it gitops friendly
**Is your feature request related to a **problem**? Please describe the **problem**.**
Git clone and commit are now bundled together into Helmex-update. This makes it impossible to use those functions in other  settings (like non-Helm GitOps).

**Describe the feature/solution you'd like**
Drop helmex-update and add support for a proper use of secrets for git cloning in `common/bash`. This will enable us to rewrite the current experiment using `helmex-update` using the following three tasks, and also other non-helm based GitOps.
1. Bash task to git clone using a token (so that 3 below becomes possible)
2. Bash task to edit yamls locally
3. Bash task to  commit / push

**Will this feature/solution bring new benefits for Iter8 users? What are they?**
Enables non-Helm based GitOps.

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Yes, please see above.

**How will this feature be tested?**
- [ ] Unit tested. E2e tested as part of tutorials. Manually tested as well.

**How will this feature be documented?**
- [ ] Iter8.tools end user documentation.

### PR DESCRIPTION
**Pull request by sriumcp**
Iter8 experiment with GitOps-y version promotion.

Fixes #943

### CODE REVIEW

**Comment by kalantar** [comment]
Comments: It isn't clear which instructions I should adapt to verify the app is running.  These instructions are in the closed note. Perhaps refer to it.

**Comment by kalantar** [comment]
I did not see a PR. Here is what I did:

Starting with and updated fork of iter8 project, I obtained the changes: 

```bash
git fetch upstream pull/993/head:pr993-1
git checkout pr993-1
```

Followed these steps:

```bash
kind create cluster --wait 5m
kubectl cluster-info --context kind-kind

kustomize build "$ITER8/install/core" | kubectl apply -f -
kubectl wait crd -l creator=iter8 --for condition=established --timeout=120s
kustomize build "$ITER8/install/builtin-metrics" | kubectl apply -f -
kubectl wait --for=condition=Ready pods --all -n iter8-system

export USERNAME=kalantar
export ITER8=$(pwd)

// already have helm and iter8ctl; verified versions

// NOTE THIS IS DIFFERENT FROM INSTRUCTIONS HERE http://localhost:8000/tutorials/deployments/slo-validation-gitops/
kubectl apply -f $ITER8/samples/deployments/app/deploy.yaml
kubectl apply -f $ITER8/samples/deployments/app/service.yaml
kubectl create ns staging
kubectl set image --local -f $ITER8/samples/deployments/app/deploy.yaml hello='gcr.io/google-samples/hello-app:2.0' -o yaml | kubectl apply -n staging -f -
kubectl apply -f $ITER8/samples/deployments/app/service.yaml -n staging

// verified that stable and candidate versions worked as expected

export GHTOKEN=<my token>
kubectl create secret generic -n staging ghtoken --from-literal=token=$GHTOKEN
kubectl create role -n staging ghtoken-reader \
  --verb=get \
  --resource=secrets \
  --resource-name=ghtoken
kubectl create rolebinding -n staging ghtoken-reader-binding \
  --role=ghtoken-reader \
  --serviceaccount=iter8-system:iter8-handlers

helm upgrade -n staging my-exp $ITER8/samples/slo-gitops \
  --set URL='http://hello.staging.svc.cluster.local:8080' \
  --set limitMeanLatency=50.0 \
  --set limitErrorRate=0.0 \
  --set limit95thPercentileLatency=100.0 \
  --set username=$USERNAME \
  --set newImage='gcr.io/google-samples/hello-app:2.0' \
  --install

// waited for completion
```
I inspected my fork and do not see any pull requests. I do see a new branch `iter8-gitops`. It contains a single commit, but no changes.

**Comment by kalantar** [comment]
I updated the instructions to install Iter8 using the local copy instead of the tagged version.

**Comment by kalantar** [comment]
This is the log from the finish task:

```
# extract token and username into env variables
export USERNAME=kalantar
export TOKEN=

# clone repo using token
git clone https://$USERNAME:$TOKEN@github.com/$USERNAME/iter8.git

# commit changes locally and push to a branch
cd iter8
git checkout -b iter8-gitops
yq e -i '.spec.template.spec.containers[0].image = "gcr.io/google-samples/hello-app:2.0"' samples/deployments/app/deploy.yaml 
git commit --allow-empty -a -m "promote candidate version to production"
git push -f origin iter8-gitops

# create pull request using credentials
echo $TOKEN > $SCRATCH_DIR/token.txt
gh auth login --with-token < $SCRATCH_DIR/token.txt
gh pr create --fill

time=2021-09-13T14:17:54Z level=trace msg=Running task: /bin/bash -c # go to scratch folder
cd $SCRATCH_DIR

# tell git who you are 
git config --global user.email "you@example.com"
git config --global user.name "Your Name"          

# extract token and username into env variables
export USERNAME=kalantar
export TOKEN=

# clone repo using token
git clone https://$USERNAME:$TOKEN@github.com/$USERNAME/iter8.git

# commit changes locally and push to a branch
cd iter8
git checkout -b iter8-gitops
yq e -i '.spec.template.spec.containers[0].image = "gcr.io/google-samples/hello-app:2.0"' samples/deployments/app/deploy.yaml 
git commit --allow-empty -a -m "promote candidate version to production"
git push -f origin iter8-gitops

# create pull request using credentials
echo $TOKEN > $SCRATCH_DIR/token.txt
gh auth login --with-token < $SCRATCH_DIR/token.txt
gh pr create --fill

time=2021-09-13T14:17:54Z level=trace msg=Got combined output: Cloning into 'iter8'...
Switched to a new branch 'iter8-gitops'
Error: stat samples/deployments/app/deploy.yaml: no such file or directory
[iter8-gitops 013d642] promote candidate version to production
remote: Invalid username or password.
fatal: Authentication failed for 'https://kalantar:@github.com/kalantar/iter8.git/'
? How would you like to authenticate GitHub CLI?  [Use arrows to move, type to filter]
> Login with a web browser
  Paste an authentication token
could not prompt: EOF
Welcome to GitHub CLI!

To authenticate, please run `gh auth login`.
```

**Comment by sriumcp** [comment]
@kalantar I believe for you to test this PR, you may need to fork my fork and try out the instructions... 

`samples/deployments/app/deploy.yaml: no such file or directory`

This file is in my fork, obviously not yet in the Iter8 repo.

**Comment by kalantar** [comment]
> This file is in my fork, obviously not yet in the Iter8 repo.

Wouldn't it be in the PR?

**Comment by sriumcp** [comment]
> Wouldn't it be in the PR?

Sorry, it is already part of the Iter8 repo. So, it is both in the main repo and my fork.

**Comment by kalantar** [comment]
Ah. My local `kalantar/iter8` was up to date with `ite8-tools/iter8` (ie, the files *were* present). However, remote `kalantar/iter8` was behind by several commits so it wasn't present there.

Instructions worked!

**Review by kalantar — DISMISSED** [review]
Finally got this to work. I think the TAG in install will need to change afterward but otherwise good.

**Pull request merged**
