### PR TITLE
assess rewards and report

### PR DESCRIPTION
**Pull request by kalantar**
Part of https://github.com/iter8-tools/iter8/issues/1414

### CODE REVIEW

**Review by sriumcp — COMMENTED** [review]
Looking good!

**Review by sriumcp — CHANGES_REQUESTED** [review]
Please include changes to `htmlreporter` also. We want rewards in both text and html.

**Review by sriumcp — APPROVED** [review]
lgtm

**Review by sriumcp — CHANGES_REQUESTED** [review]
Could we please run `iter8` as nonRoot (and set user id) in the experiment chart? This will be needed in both job and cronjob templates.

**Comment by kalantar** [comment]
> Could we please run `iter8` as nonRoot (and set user id) in the experiment chart? This will be needed in both job and cronjob templates.

The only writable files for non-root users are in `/tmp`. Moved all downloads to `/tmp' in templates.

**Review by sriumcp — APPROVED** [review]
lgtm

**Pull request merged**
