### PR TITLE
Use human-readable output in eventing and printer

### PR DESCRIPTION
**Pull request by kimikowang**

### CODE REVIEW

**Comment by kalantar** [comment]
Tests like with `test_experiment_status $EXPERIMENT "TargetsError: Err in getting candidates:"` should be updated to check `"TargetsError: Missing Candidate"`

**Comment by kalantar** [comment]
@kimikowang I'm not sure why yet, but the change (to location of iteration increment?) is preventing progress. It seems to stay stuck on iteration 0.

**Comment by kalantar** [comment]
I am watching execution and I see it working but repeated log this: ```{"level":"info","ts":1595886632.876768,"logger":"experiment-controller","msg":"IterationUpdate, Iteration 0/20 completed","namespace":"kubecon-demo","name":"productpage-abn-test"}
{"level":"info","ts":1595886633.158679,"logger":"exp```
That is, it says on iteration 0.

**Comment by kalantar** [comment]
Ah. Because we are not saving it in the status.

**Comment by kimikowang** [comment]
> @kimikowang I'm not sure why yet, but the change (to location of iteration increment?) is preventing progress. It seems to stay stuck on iteration 0.

A bug in the code. Fix has been pushed.

**Pull request merged**
