### PR TITLE
KC Grafana

### PR DESCRIPTION
**Pull request by sushmarchandran**
- Made changes to the telemetry v2, K1.16+ Grafana template to be used for Kubecon demo
- Made changes to the metrics ConfigMap to add a infinity bucket denominator for the tail latency query
- Resolves https://github.com/iter8-tools/docs/issues/147

### CODE REVIEW

**Comment by kalantar** [comment]
The change to the metrics config map works well.

**Comment by fabolive** [comment]
@sushmarchandran: Question... did you use telemetry-v2 and a Kubernetes version 1.16 or later to test your custom dashboard?

**Comment by sushmarchandran** [comment]
@fabolive Yes, the dashboard was tested in telemetry v2 and Kubernetes 1.17
@kalantar @fabolive I created a new file now. Please review.

**Comment by kalantar** [comment]
New file looks good. Question @sushmarchandran: I noticed that you had added the filter` job='envoy-stats'` to the queries. Does this mean what we have now is incorrect?

**Comment by sushmarchandran** [comment]
@kalantar I made two changes to the configmap:
1. For the tail latency query, I changed the denominator. The current (old version) of the query uses the iter8 request count query as the denominator. This produces tail latency values about 1 probably because of Prometheus approximations. I changed it to use a bucket query with a bucket value of Infinity.
2. In the numerator of the tail latency query, I noticed that the `envoy-stats` filter was repeated. So I removed one of the two duplicates.

**Pull request merged**
